<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ch.luschmar</groupId>
    <artifactId>JxA</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <properties>
        <maven.compiler.source>23</maven.compiler.source>
        <maven.compiler.target>23</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>


        <spring-boot-dependencies.version>3.4.3</spring-boot-dependencies.version>
        <maven-compiler-plugin.version>3.14.0</maven-compiler-plugin.version>
        <bcprov-jdk18on.version>1.80</bcprov-jdk18on.version>
    </properties>
    <modules>
        <module>spring-security-hawk</module>
        <module>application-jxa</module>
        <module>jxa-auth-server</module>
        <module>jxa-crypto</module>
        <module>jxa-auth-data</module>
    </modules>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot-dependencies.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.bouncycastle</groupId>
                <artifactId>bcprov-jdk18on</artifactId>
                <version>${bcprov-jdk18on.version}</version>
            </dependency>

            <!-- INTERNAL DEPENDENCIES -->
            <dependency>
                <groupId>ch.luschmar</groupId>
                <artifactId>jxa-auth-server</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>ch.luschmar</groupId>
                <artifactId>spring-security-hawk</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>ch.luschmar</groupId>
                <artifactId>jxa-crypto</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                    <configuration>
                        <compilerArgument>-parameters</compilerArgument>
                        <source>${maven.compiler.source}</source>
                        <target>${maven.compiler.target}</target>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>com.github.eirslett</groupId>
                    <artifactId>frontend-maven-plugin</artifactId>
                    <version>1.15.1</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>