spring.h2.console.enabled=true
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
#spring.jackson.deserialization.UNWRAP_SINGLE_VALUE_ARRAYS=true
spring.jackson.deserialization.USE_BIG_INTEGER_FOR_INTS=true
logging.level.org.springframework.graphql.server.webmvc=DEBUG
# spring.graphql.graphiql.enabled=true index.html!!!!
#### spring.jackson.deserialization.UNWRAP_SINGLE_VALUE_ARRAYS=true <-- TODO: this must go away... have to process query array!!!
spring.graphql.path=/api/graphql
