spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.graphql.cors.allow-credentials:true
spring.graphql.cors.allow-origins[0]:http://localhost:3030
